name: GitHub Actions build service counter image and update helm chart value file version tag

on:
  push:
    branches:
      - main
jobs:
  dockerhub-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: e119/counter-service:${{ github.sha }}
          
      - name: Update Helm values
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          yq e -i ".image.tag = \"$IMAGE_TAG\"" ./helm/values.yaml

      - name: Commit and push updated Helm values
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./helm/values.yaml
          git commit -m "Update Helm image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push
